export * from './ClientPortal/IClientPortalRepository';
export * from './SpecialOrders/ISpecialOrdersRepository';
export * from './User/IUserRepository';
export * from './Auth/IAuthRepository';
export * from './Branch/IBranchRepository';
export * from './Appointment/IAppointmentRepository';
export * from './Schedule/IScheduleRepository';
export * from './Maintenance/IMaintenanceRepository';
export * from './Customer/ICustomerRepository';
