export const API_ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    REFRESH: '/auth/refresh',
    REGISTER: '/auth/register',
  },
  USERS: {
    BASE: '/users',
    ROLES: '/users/roles',
    GENERATE_USERNAME: '/users/generate-username',
    CHECK_USERNAME: '/users/check-username',
    MIGRATE_USERNAMES: '/users/migrate-usernames',
    BY_ID: (id: string) => `/users/${id}`,
    UPDATE_PASSWORD: (id: string) => `/users/${id}/password`,
  },
  SESSIONS: {
    BASE: '/sessions',
    BY_ID: (id: string) => `/sessions/${id}`,
    BY_USER: (userId: string) => `/sessions/user/${userId}`,
  },
  BRANCHES: {
    BASE: '/branches',
    PUBLIC: '/branches/public',
    USER: '/branches/user',
    ACTIVE: '/branches/active',
    BY_ID: (id: string) => `/branches/${id}`,
  },
  APPOINTMENTS: {
    BASE: '/appointments',
    PUBLIC: '/appointments/public',
    PUBLIC_STATUS: '/appointments/public/status',
    TIMELINE: '/appointments/timeline',
    BY_ID: (id: string) => `/appointments/${id}`,
    APPROVE: (id: string) => `/appointments/${id}/approve`,
    REJECT: (id: string) => `/appointments/${id}/reject`,
    RESCHEDULE: (id: string) => `/appointments/${id}/reschedule`,
    CHECK_IN: (id: string) => `/appointments/${id}/check-in`,
    NO_SHOW: (id: string) => `/appointments/${id}/no-show`,
    DIRECT_RECEPTION: '/maintenance/direct-reception',
    SCHEDULE: '/appointments/schedule',
    HOLIDAYS: '/appointments/holidays',
    HOLIDAY_BY_ID: (id: string) => `/appointments/holidays/${id}`,
    OCCUPIED_SLOTS: '/appointments/occupied-slots',
  },
  MAINTENANCE: {
    BASE: '/maintenance',
    BY_ID: (id: string) => `/maintenance/${id}`,
    NOTIFY: (id: string) => `/maintenance/${id}/notify`,
    NOTES: (id: string) => `/maintenance/${id}/notes`,
    ITEMS: (id: string) => `/maintenance/${id}/items`,
    EVIDENCE: (id: string) => `/maintenance/${id}/evidence`,
    LINK_SALE: (id: string) => `/maintenance/${id}/link-sale`,
    UNLINK_SALE: (id: string) => `/maintenance/${id}/unlink-sale`,
    DIRECT_RECEPTION: '/maintenance/direct-reception',
    TRACK_PUBLIC: '/maintenance/track/public',
    PDF: (id: string) => `/maintenance/${id}/pdf`,
  },
  CUSTOMERS: {
    BASE: '/customers',
    LOOKUP: '/customers/lookup',
    BY_PHONE: (phone: string) => `/customers/phone/${phone}`,
    BY_ID: (id: string) => `/customers/${id}`,
  },
  VEHICLES: {
    BASE: '/vehicles',
    BY_CUSTOMER: (customerId: string) => `/vehicles/by-customer/${customerId}`,
    BY_ID: (id: string) => `/vehicles/${id}`,
  },
  INVENTORY: {
    PRODUCTS: '/inventory/products',
    PRODUCT_BY_ID: (id: string) => `/inventory/products/${id}`,
    BRANDS: '/inventory/brands',
    BRAND_BY_ID: (id: string) => `/inventory/brands/${id}`,
    CATEGORIES: '/inventory/categories',
    CATEGORY_BY_ID: (id: string) => `/inventory/categories/${id}`,
    PROVIDERS: '/inventory/providers',
    PROVIDER_BY_ID: (id: string) => `/inventory/providers/${id}`,
    MOVEMENTS: '/inventory/movements',
    PRODUCT_MOVEMENTS: (id: string) => `/inventory/products/${id}/movements`,
    RECEPTIONS: '/inventory/receptions',
    RECEPTION_BY_ID: (id: string) => `/inventory/receptions/${id}`,
    APPROVE_RECEPTION: (id: string) => `/inventory/receptions/${id}/approve`,
    REJECT_RECEPTION: (id: string) => `/inventory/receptions/${id}/reject`,
    OPEN_BOX: '/inventory/boxes/open',
    STATS: '/inventory/stats',
  },
  SALES: {
    BASE: '/sales',
    BY_ID: (id: string) => `/sales/${id}`,
    CANCEL: (id: string) => `/sales/${id}/cancel`,
    LINK_ORDER: (id: string) => `/sales/${id}/link-order`,
    DAILY_SUMMARY: '/sales/summary/daily',
  },
  QUOTES: {
    BASE: '/quotes',
    BY_ID: (id: string) => `/quotes/${id}`,
    CONVERT_TO_SALE: (id: string) => `/quotes/${id}/convert-to-sale`,
  },
  SERVICES: {
    BASE: '/services',
    BY_ID: (id: string) => `/services/${id}`,
  },
  ORDERS: {
    BASE: '/orders',
    SUMMARY: '/orders/summary',
    BY_ID: (id: string) => `/orders/${id}`,
    PAYMENTS: (id: string) => `/orders/${id}/payments`,
    STATUS: (id: string) => `/orders/${id}/status`,
    CANCEL: (id: string) => `/orders/${id}/cancel`,
  },
  ATTENDANCE: {
    CHECK_IN: '/attendance/check-in',
    CHECK_OUT: '/attendance/check-out',
    CLOCK_IN: '/attendance/clock-in',
    CLOCK_OUT: '/attendance/clock-out',
    BREAK_START: '/attendance/break/start',
    BREAK_END: '/attendance/break/end',
    TODAY: '/attendance/today',
    BRANCH_TODAY: '/attendance/branch/today',
    MY_RECORDS: '/attendance/my-records',
    MY_STATUS: '/attendance/my-status',
    RECORDS: '/attendance/records',
    SUMMARY: '/attendance/summary',
    ADMIN_RECORDS: '/attendance/admin/records',
    ADMIN_SUMMARY: '/attendance/admin/summary',
    ADMIN_USER_BREAKDOWN: (userId: string) => `/attendance/admin/user-breakdown/${userId}`,
    ADMIN_RECORD_BY_ID: (id: string) => `/attendance/admin/${id}`,
    BY_USER: (userId: string) => `/attendance/user/${userId}`,
    BY_ID: (id: string) => `/attendance/${id}`,
    KIOSK_EMPLOYEES: '/attendance/kiosk/employees',
    KIOSK_CLOCK: '/attendance/kiosk/clock',
  },
  AUDIT_LOGS: {
    BASE: '/audit-logs',
    BY_ENTITY: (entityId: string) => `/audit-logs/entity/${entityId}`,
  },
  REPORTS: {
    FINANCIAL: '/reports/financial',
    TOP_PRODUCTS: '/reports/top-products',
    MECHANIC_PRODUCTIVITY: '/reports/mechanic-productivity',
    OPERATIONS_SUMMARY: '/dashboard/operations-summary',
  },
  SYSTEM: {
    MIGRATE_BRANCHES: '/system/migration/branches',
  },
} as const;

